[dash]
title = "MTA Ridership Explorer: Trends and Post-Pandemic Recovery"
subtitle = "An interactive dashboard to explore MTA ridership trends and post-pandemic recovery"
page_title = "MTA Ridership Explorer by taruma"
loading_message = "Updating..."
debug = true
alias = "taruma-mtadash"

[template]
theme = "FLATLY"
watermark_source = ""

[repository]
github_url = "https://github.com/taruma/mtadash"
github_repo = "taruma/mtadash"