[dash]
title = "MTA Dash App"
page_title = "taruma-mtadash | MTA DASH"
loading_message = "Updating..."
debug = true
alias = "taruma-mtadash"

[template]
theme = "FLATLY"

[repository]
github_url = "https://github.com/taruma/mtadash"
github_repo = "taruma/mtadash"