[dash]
title = "MTA Ridership Explorer: Trends and Post-Pandemic Recovery"
subtitle = "An interactive dashboard to explore MTA ridership trends and post-pandemic recovery"
page_title = "MTA Ridership Explorer by taruma"
loading_message = "Updating..."
debug = false
alias = "taruma-mtadash"

[template]
theme = "JOURNAL"
watermark_source = ""

[repository]
github_url = "https://github.com/taruma/mta-dash"
github_repo = "taruma/mta-dash"