[dash]
title = "Metrik Metro App"
page_title = "taruma-mtadash | MTA DASH"
loading_text = "Updating..."
debug = true
alias = "taruma-mtadash"

[template]
watermark_source = ""
theme = "MATERIA"

[repository]
github_url = "https://github.com/taruma/mtadash"
github_repo = "taruma/mtadash"